// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelSz7vqvyKBCwYZ-YMmhmVdWJuQUvhU4',
    appId: '1:900933622312:web:d47b217f3e413f3cf2331d',
    messagingSenderId: '900933622312',
    projectId: 'riegameapp-4d5b7',
    authDomain: 'riegameapp-4d5b7.firebaseapp.com',
    storageBucket: 'riegameapp-4d5b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbCXpw-v5RH5U9UK-SNgbC3B8w-J72Jw',
    appId: '1:900933622312:android:eebf70e96e799133f2331d',
    messagingSenderId: '900933622312',
    projectId: 'riegameapp-4d5b7',
    storageBucket: 'riegameapp-4d5b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEWvEpIegrEx26czoPaR0De6bZfDh5A28',
    appId: '1:900933622312:ios:5a0a9aa411b57af0f2331d',
    messagingSenderId: '900933622312',
    projectId: 'riegameapp-4d5b7',
    storageBucket: 'riegameapp-4d5b7.firebasestorage.app',
    iosBundleId: 'com.example.riegame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEWvEpIegrEx26czoPaR0De6bZfDh5A28',
    appId: '1:900933622312:ios:5a0a9aa411b57af0f2331d',
    messagingSenderId: '900933622312',
    projectId: 'riegameapp-4d5b7',
    storageBucket: 'riegameapp-4d5b7.firebasestorage.app',
    iosBundleId: 'com.example.riegame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDelSz7vqvyKBCwYZ-YMmhmVdWJuQUvhU4',
    appId: '1:900933622312:web:88f33b5a0a033c3bf2331d',
    messagingSenderId: '900933622312',
    projectId: 'riegameapp-4d5b7',
    authDomain: 'riegameapp-4d5b7.firebaseapp.com',
    storageBucket: 'riegameapp-4d5b7.firebasestorage.app',
  );
}
